//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yushko.ExRates {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nbrb.by/", ConfigurationName="ExRates.ExRatesSoap")]
    public interface ExRatesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/CurrenciesRefDaily", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CurrenciesRefDaily();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/CurrenciesRefDaily", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CurrenciesRefDailyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/CurrenciesRefMonthly", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CurrenciesRefMonthly();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/CurrenciesRefMonthly", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CurrenciesRefMonthlyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/StartDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime StartDate(int Periodicity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/StartDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> StartDateAsync(int Periodicity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/LastDailyExRatesDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime LastDailyExRatesDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/LastDailyExRatesDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> LastDailyExRatesDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/LastMonthlyExRatesDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime LastMonthlyExRatesDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/LastMonthlyExRatesDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> LastMonthlyExRatesDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/ExRatesDaily", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExRatesDaily(System.DateTime onDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/ExRatesDaily", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ExRatesDailyAsync(System.DateTime onDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/ExRatesMonthly", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExRatesMonthly(System.DateTime onDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/ExRatesMonthly", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ExRatesMonthlyAsync(System.DateTime onDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/ExRatesDyn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExRatesDyn(int curId, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/ExRatesDyn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ExRatesDynAsync(int curId, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/CurrenciesRef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CurrenciesRef(int Periodicity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/CurrenciesRef", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CurrenciesRefAsync(int Periodicity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/MetalsLastDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime MetalsLastDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/MetalsLastDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> MetalsLastDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/MetalsRef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MetalsRef();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/MetalsRef", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MetalsRefAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/MetalsPrices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MetalsPrices(int MetalId, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/MetalsPrices", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MetalsPricesAsync(int MetalId, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/IngotsPrices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IngotsPrices(System.DateTime onDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/IngotsPrices", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IngotsPricesAsync(System.DateTime onDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/IngotsLastDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime IngotsLastDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/IngotsLastDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> IngotsLastDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/StockAddRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet StockAddRates(System.DateTime onDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/StockAddRates", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> StockAddRatesAsync(System.DateTime onDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/StockAddRatesLastDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime StockAddRatesLastDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/StockAddRatesLastDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> StockAddRatesLastDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/RefRateOnDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RefRateOnDate(System.DateTime onDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/RefRateOnDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RefRateOnDateAsync(System.DateTime onDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/RefRateDyn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RefRateDyn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nbrb.by/RefRateDyn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RefRateDynAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExRatesSoapChannel : Yushko.ExRates.ExRatesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExRatesSoapClient : System.ServiceModel.ClientBase<Yushko.ExRates.ExRatesSoap>, Yushko.ExRates.ExRatesSoap {
        
        public ExRatesSoapClient() {
        }
        
        public ExRatesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExRatesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExRatesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExRatesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet CurrenciesRefDaily() {
            return base.Channel.CurrenciesRefDaily();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CurrenciesRefDailyAsync() {
            return base.Channel.CurrenciesRefDailyAsync();
        }
        
        public System.Data.DataSet CurrenciesRefMonthly() {
            return base.Channel.CurrenciesRefMonthly();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CurrenciesRefMonthlyAsync() {
            return base.Channel.CurrenciesRefMonthlyAsync();
        }
        
        public System.DateTime StartDate(int Periodicity) {
            return base.Channel.StartDate(Periodicity);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> StartDateAsync(int Periodicity) {
            return base.Channel.StartDateAsync(Periodicity);
        }
        
        public System.DateTime LastDailyExRatesDate() {
            return base.Channel.LastDailyExRatesDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> LastDailyExRatesDateAsync() {
            return base.Channel.LastDailyExRatesDateAsync();
        }
        
        public System.DateTime LastMonthlyExRatesDate() {
            return base.Channel.LastMonthlyExRatesDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> LastMonthlyExRatesDateAsync() {
            return base.Channel.LastMonthlyExRatesDateAsync();
        }
        
        public System.Data.DataSet ExRatesDaily(System.DateTime onDate) {
            return base.Channel.ExRatesDaily(onDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ExRatesDailyAsync(System.DateTime onDate) {
            return base.Channel.ExRatesDailyAsync(onDate);
        }
        
        public System.Data.DataSet ExRatesMonthly(System.DateTime onDate) {
            return base.Channel.ExRatesMonthly(onDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ExRatesMonthlyAsync(System.DateTime onDate) {
            return base.Channel.ExRatesMonthlyAsync(onDate);
        }
        
        public System.Data.DataSet ExRatesDyn(int curId, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.ExRatesDyn(curId, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ExRatesDynAsync(int curId, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.ExRatesDynAsync(curId, fromDate, toDate);
        }
        
        public System.Data.DataSet CurrenciesRef(int Periodicity) {
            return base.Channel.CurrenciesRef(Periodicity);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CurrenciesRefAsync(int Periodicity) {
            return base.Channel.CurrenciesRefAsync(Periodicity);
        }
        
        public System.DateTime MetalsLastDate() {
            return base.Channel.MetalsLastDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> MetalsLastDateAsync() {
            return base.Channel.MetalsLastDateAsync();
        }
        
        public System.Data.DataSet MetalsRef() {
            return base.Channel.MetalsRef();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MetalsRefAsync() {
            return base.Channel.MetalsRefAsync();
        }
        
        public System.Data.DataSet MetalsPrices(int MetalId, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.MetalsPrices(MetalId, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MetalsPricesAsync(int MetalId, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.MetalsPricesAsync(MetalId, fromDate, toDate);
        }
        
        public System.Data.DataSet IngotsPrices(System.DateTime onDate) {
            return base.Channel.IngotsPrices(onDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IngotsPricesAsync(System.DateTime onDate) {
            return base.Channel.IngotsPricesAsync(onDate);
        }
        
        public System.DateTime IngotsLastDate() {
            return base.Channel.IngotsLastDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> IngotsLastDateAsync() {
            return base.Channel.IngotsLastDateAsync();
        }
        
        public System.Data.DataSet StockAddRates(System.DateTime onDate) {
            return base.Channel.StockAddRates(onDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> StockAddRatesAsync(System.DateTime onDate) {
            return base.Channel.StockAddRatesAsync(onDate);
        }
        
        public System.DateTime StockAddRatesLastDate() {
            return base.Channel.StockAddRatesLastDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> StockAddRatesLastDateAsync() {
            return base.Channel.StockAddRatesLastDateAsync();
        }
        
        public System.Data.DataSet RefRateOnDate(System.DateTime onDate) {
            return base.Channel.RefRateOnDate(onDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RefRateOnDateAsync(System.DateTime onDate) {
            return base.Channel.RefRateOnDateAsync(onDate);
        }
        
        public System.Data.DataSet RefRateDyn() {
            return base.Channel.RefRateDyn();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RefRateDynAsync() {
            return base.Channel.RefRateDynAsync();
        }
    }
}
